/*
Step 1: Configure access permissions for the S3 bucket

AWS access control requirements
Snowflake requires the following permissions on an S3 bucket and folder to be able to access files in the folder (and sub-folders):

- s3:GetBucketLocation
- s3:GetObject
- s3:GetObjectVersion
- s3:ListBucket

Note
The following additional permissions are required to perform additional SQL actions:

- Permission       SQL Action

  s3:PutObject     Unload files to the bucket
  s3:DeleteObject  Either automatically purge files from the stage after a successful load 
                   or execute REMOVE statements to remove files manually.

As a best practice, Snowflake recommends creating an IAM policy for Snowflake access to the S3 bucket. 
You can then attach the policy to the role and use the security credentials generated by AWS for the role to access files in the bucket.

POLICY (attach to) --> ROLE (use) SECURITY CREDENTIALS generated by AWS for the role to access files in the bucket.


REF: https://docs.snowflake.com/en/user-guide/data-load-snowpipe-auto-s3
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~ 1           CREATE POLICY
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectVersion"
            ],
            "Resource": "arn:aws:s3:::d . . . /*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": "arn:aws:s3:::dean-test-snowpipe",
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "reltio/*"
                    ]
                }
            }
        }
    ]
}

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~ 2         CREATE IAM ROLE
       (ATTACH POLICY TO THE ROLE)

1. Create a shell IAM role (no specific information
about External ID this will be added later)
2. Attach the POLICY
3. Create an INTEGRATION object in Snowflake
   3.1. use STORAGE_AWS_ROLE_ARN = <The IAM role name>
   3.2. Get the Snowflake's IAM user. We need that user to
        be added to our IAM role thrust..
4. Grant the SF IAM user Permissions to access S3
   4.1. Test if the integration object can interact with 
        the S3 and perform all granted actions ..
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#### 3.1. snowflake - integration object ###

CREATE OR REPLACE  STORAGE INTEGRATION  AWS_STORAGE_INTEGRATION
  TYPE = EXTERNAL_STAGE
  ENABLED = TRUE
  STORAGE_ALLOWED_LOCATIONS = ('s3:// .../') -- THIS IS THE LIST 
  COMMENT = 'Dean, S3 storage integration'
  -- specific to AWS S3
  STORAGE_PROVIDER = 'S3'
  STORAGE_AWS_ROLE_ARN = '....role/DeansSnowflakeRole'
  STORAGE_AWS_EXTERNAL_ID = '...'
  
  ---(optional - SF auto-generate if not explicitly provided) STORAGE_AWS_EXTERNAL_ID = '...'
  -- This is an external ID we created and needs to be referenced in the thrust policy in the IAM role.
  -- REF: https://docs.snowflake.com/en/sql-reference/sql/create-storage-integration#label-create-storage-integration-aws-ext-id

### 3.2 snowflake - get SF IAM user
DESCRIBE STORAGE INTEGRATION AWS_STORAGE_INTEGRATION;

STORAGE_AWS_IAM_USER_ARN :  ...
STORAGE_AWS_ROLE_ARN     :  ...role/DeansSnowflakeRole  (ARN of the AWS ROLE defined above)
STORAGE_AWS_EXTERNAL_ID  :  ...

STORAGE_AWS_IAM_USER_ARN
    The AWS IAM user created for your Snowflake account; 
    Snowflake provisions a single IAM user for your entire Snowflake account. 
    All S3 storage integrations in your account use that IAM user.

STORAGE_AWS_EXTERNAL_ID
    The external ID that Snowflake uses to establish a trust relationship with AWS. 
    If you didn’t specify an external ID (STORAGE_AWS_EXTERNAL_ID) when you created the storage integration, 
    Snowflake generates an ID for you to use.



#### 4. Grant the SF IAM user Permissions (ROLE Thrust policy) to access S3 ###

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "... snowflake iam user arn ..."
            },
            "Action": "sts:AssumeRole",
            "Condition": {
                "StringEquals": {
                    "sts:ExternalId": "..."
                }
            }
        }
    ]
}

##### 4.1. Test policy (test if SF can access S3 and perform all granted actions)
## ref: https://docs.snowflake.com/en/sql-reference/functions/system_validate_storage_integration
select SYSTEM$VALIDATE_STORAGE_INTEGRATION(
        'AWS_STORAGE_INTEGRATION',
        's3://dean-test-snowpipe/ . . . ',
        'sample_users_with_id_1.gz',
        'read'        
)

--------------------------------------------------

*/